 - name: Playbook Base
   hosts: servers
   tasks:
     - name: Ping
       ansible.builtin.ping:
     - name: Update Cache
       community.general.apk:
         update_cache: true
     - name: Upgrade
       community.general.apk:
         upgrade: true
     - name: Install Python3
       community.general.apk:
          name: python3
          state: present
     - name: Install Docker + Docker Compose
       community.general.apk:
         name: docker,docker-cli-compose
         state: present
   become: true
   become_method: doas
       
